import os
import sys
import json
import pandas as pd

# Ensure src root is in python path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.log_utils import get_logger
from config import (
    CLEANED_PROVINCES_CSV,
    CLUSTERED_REGENCIES_CSV,
    EVALUATE_METRICS_JSON,
    INTERPRET_REPORT_MD,
    INTERPRET_LABELS_JSON,
    SEED_SQL
)

logger = get_logger("deployment.seed")

def escape_sql(val):
    if val is None or pd.isna(val):
        return "NULL"
    if isinstance(val, str):
        return "'" + val.replace("'", "''") + "'"
    return str(val)

def main():
    logger.info("Memulai Pembuatan Script Seeding Database D1 (CRISP-DM Deployment)...")
    sql_lines = ["-- Seed data generated by src/deployment/seed.py\n"]

    # 1. Provinces
    if os.path.exists(CLEANED_PROVINCES_CSV):
        logger.info("Membaca data Provinsi bersih...")
        df_prov = pd.read_csv(CLEANED_PROVINCES_CSV)
        sql_lines.append("-- Seed Provinces")
        for _, row in df_prov.iterrows():
            p_id = int(row.get("province_id", 0))
            name = str(row.get("province_name", ""))
            total_kop = int(row.get("total_koperasi", 0)) if not pd.isna(row.get("total_koperasi")) else 0
            nib = int(row.get("koperasi_nib", 0)) if not pd.isna(row.get("koperasi_nib")) else 0
            npwp = int(row.get("koperasi_npwp", 0)) if not pd.isna(row.get("koperasi_npwp")) else 0
            rat = int(row.get("koperasi_rat", 0)) if not pd.isna(row.get("koperasi_rat")) else 0
            r_nib = float(row.get("rasio_nib", 0.0)) if not pd.isna(row.get("rasio_nib")) else 0.0
            r_npwp = float(row.get("rasio_npwp", 0.0)) if not pd.isna(row.get("rasio_npwp")) else 0.0
            r_rat = float(row.get("rasio_rat", 0.0)) if not pd.isna(row.get("rasio_rat")) else 0.0
            pokok = float(row.get("simpanan_pokok", 0.0)) if not pd.isna(row.get("simpanan_pokok")) else 0.0
            wajib = float(row.get("simpanan_wajib", 0.0)) if not pd.isna(row.get("simpanan_wajib")) else 0.0
            vol = float(row.get("volume_transaksi", 0.0)) if not pd.isna(row.get("volume_transaksi")) else 0.0
            nilai = float(row.get("nilai_transaksi", 0.0)) if not pd.isna(row.get("nilai_transaksi")) else 0.0
            lat = float(row.get("latitude", 0.0)) if not pd.isna(row.get("latitude")) else 0.0
            lon = float(row.get("longitude", 0.0)) if not pd.isna(row.get("longitude")) else 0.0

            sql_lines.append(
                f"INSERT OR REPLACE INTO provinces (id, province_name, total_koperasi, koperasi_nib, koperasi_npwp, koperasi_rat, rasio_nib, rasio_npwp, rasio_rat, simpanan_pokok, simpanan_wajib, volume_transaksi, nilai_transaksi, latitude, longitude) "
                f"VALUES ({p_id}, {escape_sql(name)}, {total_kop}, {nib}, {npwp}, {rat}, {r_nib}, {r_npwp}, {r_rat}, {pokok}, {wajib}, {vol}, {nilai}, {lat}, {lon});"
            )
        sql_lines.append("")

    # 2. Regencies
    if os.path.exists(CLUSTERED_REGENCIES_CSV):
        logger.info("Membaca data Kabupaten/Kota terklasterisasi...")
        df_reg = pd.read_csv(CLUSTERED_REGENCIES_CSV)
        sql_lines.append("-- Seed Regencies")
        for _, row in df_reg.iterrows():
            prov_id = int(row.get("province_id", 0))
            reg_no = int(row.get("regency_no", 0))
            r_id = prov_id * 1000 + reg_no
            name = str(row.get("regency_name", ""))
            total_kop = int(row.get("total_koperasi", 0)) if not pd.isna(row.get("total_koperasi")) else 0
            nib = int(row.get("koperasi_nib", 0)) if not pd.isna(row.get("koperasi_nib")) else 0
            npwp = int(row.get("koperasi_npwp", 0)) if not pd.isna(row.get("koperasi_npwp")) else 0
            rat = int(row.get("koperasi_rat", 0)) if not pd.isna(row.get("koperasi_rat")) else 0
            r_nib = float(row.get("rasio_nib", 0.0)) if not pd.isna(row.get("rasio_nib")) else 0.0
            r_npwp = float(row.get("rasio_npwp", 0.0)) if not pd.isna(row.get("rasio_npwp")) else 0.0
            r_rat = float(row.get("rasio_rat", 0.0)) if not pd.isna(row.get("rasio_rat")) else 0.0
            pokok = float(row.get("simpanan_pokok", 0.0)) if not pd.isna(row.get("simpanan_pokok")) else 0.0
            wajib = float(row.get("simpanan_wajib", 0.0)) if not pd.isna(row.get("simpanan_wajib")) else 0.0
            vol = float(row.get("volume_transaksi", 0.0)) if not pd.isna(row.get("volume_transaksi")) else 0.0
            nilai = float(row.get("nilai_transaksi", 0.0)) if not pd.isna(row.get("nilai_transaksi")) else 0.0
            label = int(row.get("cluster_label", 0)) if not pd.isna(row.get("cluster_label")) else 0
            lat = float(row.get("latitude", 0.0)) if not pd.isna(row.get("latitude")) else 0.0
            lon = float(row.get("longitude", 0.0)) if not pd.isna(row.get("longitude")) else 0.0

            sql_lines.append(
                f"INSERT OR REPLACE INTO regencies (id, province_id, regency_name, total_koperasi, koperasi_nib, koperasi_npwp, koperasi_rat, rasio_nib, rasio_npwp, rasio_rat, simpanan_pokok, simpanan_wajib, volume_transaksi, nilai_transaksi, cluster_label, latitude, longitude) "
                f"VALUES ({r_id}, {prov_id}, {escape_sql(name)}, {total_kop}, {nib}, {npwp}, {rat}, {r_nib}, {r_npwp}, {r_rat}, {pokok}, {wajib}, {vol}, {nilai}, {label}, {lat}, {lon});"
            )
        sql_lines.append("")

    # 3. Metrics
    if os.path.exists(EVALUATE_METRICS_JSON):
        logger.info("Membaca data Metrik Evaluasi...")
        sql_lines.append("-- Seed Metrics")
        with open(EVALUATE_METRICS_JSON, "r", encoding="utf-8") as f:
            metrics_data = json.load(f)
        metrics_obj = metrics_data.get("clustering_metrics", {})
        for key, val in metrics_obj.items():
            if val is not None:
                sql_lines.append(
                    f"INSERT OR REPLACE INTO metrics (key, value) "
                    f"VALUES ({escape_sql(key)}, {escape_sql(str(val))});"
                )
        sql_lines.append("")

    # 4. AI Report
    if os.path.exists(INTERPRET_REPORT_MD) and os.path.exists(INTERPRET_LABELS_JSON):
        logger.info("Membaca data Laporan AI...")
        sql_lines.append("-- Seed AI Report")
        with open(INTERPRET_REPORT_MD, "r", encoding="utf-8") as f:
            report_text = f.read()
        with open(INTERPRET_LABELS_JSON, "r", encoding="utf-8") as f:
            labels_json = f.read()
        sql_lines.append(
            f"INSERT OR REPLACE INTO ai_report (id, report_text, labels_json) "
            f"VALUES (1, {escape_sql(report_text)}, {escape_sql(labels_json)});"
        )
        sql_lines.append("")

    # Write to seed.sql
    os.makedirs(os.path.dirname(SEED_SQL), exist_ok=True)
    with open(SEED_SQL, 'w', encoding='utf-8') as f:
        f.write("\n".join(sql_lines))
    logger.info(f"SQL seed file generated at: {SEED_SQL}")

if __name__ == "__main__":
    main()
