stages:
  scrape_provinces:
    cmd: python scrape/scrape_provinces.py
    deps:
      - scrape/scrape_provinces.py
      - scrape/scraper_utils.py
    outs:
      - data/scraped_provinces.csv

  scrape_districts:
    cmd: python scrape/scrape_districts.py
    deps:
      - scrape/scrape_districts.py
      - scrape/scraper_utils.py
    outs:
      - data/scraped_districts.csv
