[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kopdes"
version = "1.0.0"
description = "CRISP-DM Analytics & MLOps Pipeline for SIMKOPDES"
authors = [{ name = "Qoriib" }]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["notebooks"]
