const fs = require('fs');
const path = require('path');

// Helper to escape single quotes in SQL
function escapeSQL(str) {
  if (!str) return '';
  return str.replace(/'/g, "''");
}

// Simple CSV Parser
function parseCSV(content) {
  const lines = content.split(/\r?\n/).map(l => l.trim()).filter(Boolean);
  if (lines.length === 0) return [];
  
  const headers = lines[0].split(',');
  const rows = [];
  
  for (let i = 1; i < lines.length; i++) {
    const currentLine = lines[i];
    const values = [];
    let insideQuote = false;
    let currentValue = '';
    
    for (let c = 0; c < currentLine.length; c++) {
      const char = currentLine[c];
      if (char === '"') {
        insideQuote = !insideQuote;
      } else if (char === ',' && !insideQuote) {
        values.push(currentValue.trim());
        currentValue = '';
      } else {
        currentValue += char;
      }
    }
    values.push(currentValue.trim());
    
    const row = {};
    headers.forEach((header, index) => {
      row[header.trim()] = values[index] || '';
    });
    rows.push(row);
  }
  return rows;
}

function main() {
  const baseDir = path.join(__dirname, '..', '..', '..');
  
  const provPath = path.join(baseDir, 'data', 'transform', 'transformed_provinces.csv');
  const regPath = path.join(baseDir, 'data', 'model', 'clustered_regencies.csv');
  const metricsPath = path.join(baseDir, 'reports', 'evaluate_metrics.json');
  const aiReportPath = path.join(baseDir, 'reports', 'interpret_report.md');
  const aiLabelsPath = path.join(baseDir, 'reports', 'interpret_labels.json');
  
  let sql = '-- Seed data generated by seed.cjs\n\n';
  
  // 1. Seed Provinces
  if (fs.existsSync(provPath)) {
    const provCSV = fs.readFileSync(provPath, 'utf8');
    const provRows = parseCSV(provCSV);
    
    sql += '-- Seed Provinces\n';
    provRows.forEach(row => {
      const id = row.province_id;
      const name = escapeSQL(row.province_name);
      const count = parseInt(row.jumlah_koperasi) || 0;
      const nib = parseInt(row.koperasi_nib) || 0;
      const npwp = parseInt(row.koperasi_npwp) || 0;
      const rat = parseInt(row.koperasi_rat) || 0;
      
      sql += `INSERT OR REPLACE INTO provinces (id, province_name, jumlah_koperasi, koperasi_nib, koperasi_npwp, koperasi_rat) VALUES (${id}, '${name}', ${count}, ${nib}, ${npwp}, ${rat});\n`;
    });
    sql += '\n';
  } else {
    console.error(`Province data not found: ${provPath}`);
  }
  
  // 2. Seed Regencies
  if (fs.existsSync(regPath)) {
    const regCSV = fs.readFileSync(regPath, 'utf8');
    const regRows = parseCSV(regCSV);
    
    sql += '-- Seed Regencies\n';
    regRows.forEach(row => {
      const provId = row.province_id;
      const regNo = row.regency_no;
      const id = parseInt(provId) * 1000 + parseInt(regNo);
      const name = escapeSQL(row.regency_name);
      const count = parseInt(row.jumlah_koperasi) || 0;
      const nib = parseInt(row.koperasi_nib) || 0;
      const npwp = parseInt(row.koperasi_npwp) || 0;
      const rat = parseInt(row.koperasi_rat) || 0;
      const val = parseFloat(row.nilai_transaksi) || 0.0;
      const label = parseInt(row.cluster_label) || 0;
      
      sql += `INSERT OR REPLACE INTO regencies (id, province_id, regency_name, jumlah_koperasi, koperasi_nib, koperasi_npwp, koperasi_rat, nilai_transaksi, cluster_label) VALUES (${id}, ${provId}, '${name}', ${count}, ${nib}, ${npwp}, ${rat}, ${val}, ${label});\n`;
    });
    sql += '\n';
  } else {
    console.error(`Regency data not found: ${regPath}`);
  }
  
  // 3. Seed Metrics
  if (fs.existsSync(metricsPath)) {
    const metricsData = JSON.parse(fs.readFileSync(metricsPath, 'utf8'));
    
    sql += '-- Seed Metrics\n';
    const flatMetrics = {
      'silhouette_score': metricsData.clustering_metrics?.silhouette_score,
      'calinski_harabasz_index': metricsData.clustering_metrics?.calinski_harabasz_index,
      'davies_bouldin_index': metricsData.clustering_metrics?.davies_bouldin_index,
      'number_of_clusters': metricsData.clustering_metrics?.number_of_clusters
    };
    
    Object.keys(flatMetrics).forEach(key => {
      const val = flatMetrics[key];
      if (val !== undefined) {
        sql += `INSERT OR REPLACE INTO metrics (key, value) VALUES ('${key}', '${val}');\n`;
      }
    });
    sql += '\n';
  }
  
  // 4. Seed AI Report
  if (fs.existsSync(aiReportPath) && fs.existsSync(aiLabelsPath)) {
    const reportText = fs.readFileSync(aiReportPath, 'utf8');
    const labelsJson = fs.readFileSync(aiLabelsPath, 'utf8');
    
    sql += '-- Seed AI Report\n';
    sql += `INSERT OR REPLACE INTO ai_report (id, report_text, labels_json) VALUES (1, '${escapeSQL(reportText)}', '${escapeSQL(labelsJson)}');\n`;
  }
  
  const outputPath = path.join(__dirname, 'seed.sql');
  fs.writeFileSync(outputPath, sql, 'utf8');
  console.log(`[SUCCESS] Seed SQL generated at: ${outputPath}`);
}

main();
