import os
import json
import pandas as pd

from config import (
    TRANSFORMED_PROVINCES_CSV,
    CLUSTERED_REGENCIES_CSV,
    MODEL_METRICS_JSON,
    AI_REPORT_MD,
    AI_LABELS_JSON,
    SEED_SQL
)
from utils.log_utils import get_logger

logger = get_logger("store")

def escape_sql(val):
    if val is None or pd.isna(val):
        return "NULL"
    if isinstance(val, str):
        return "'" + val.replace("'", "''") + "'"
    return str(val)

def main():
    sql_lines = ["-- Seed data generated by src/store.py\n"]
    
    # 1. Provinces
    if os.path.exists(TRANSFORMED_PROVINCES_CSV):
        logger.info("Membaca data Provinsi...")
        df_prov = pd.read_csv(TRANSFORMED_PROVINCES_CSV)
        sql_lines.append("-- Seed Provinces")
        for _, row in df_prov.iterrows():
            p_id = int(row["province_id"])
            name = str(row["province_name"])
            count = int(row["jumlah_koperasi"]) if not pd.isna(row["jumlah_koperasi"]) else 0
            nib = int(row["koperasi_nib"]) if not pd.isna(row["koperasi_nib"]) else 0
            npwp = int(row["koperasi_npwp"]) if not pd.isna(row["koperasi_npwp"]) else 0
            rat = int(row["koperasi_rat"]) if not pd.isna(row["koperasi_rat"]) else 0
            sql_lines.append(
                f"INSERT OR REPLACE INTO provinces (id, province_name, jumlah_koperasi, koperasi_nib, koperasi_npwp, koperasi_rat) "
                f"VALUES ({p_id}, {escape_sql(name)}, {count}, {nib}, {npwp}, {rat});"
            )
        sql_lines.append("")
        
    # 2. Regencies
    if os.path.exists(CLUSTERED_REGENCIES_CSV):
        logger.info("Membaca data Kabupaten/Kota...")
        df_reg = pd.read_csv(CLUSTERED_REGENCIES_CSV)
        sql_lines.append("-- Seed Regencies")
        for _, row in df_reg.iterrows():
            prov_id = int(row["province_id"])
            reg_no = int(row["regency_no"])
            r_id = prov_id * 1000 + reg_no
            name = str(row["regency_name"])
            count = int(row["jumlah_koperasi"]) if not pd.isna(row["jumlah_koperasi"]) else 0
            nib = int(row["koperasi_nib"]) if not pd.isna(row["koperasi_nib"]) else 0
            npwp = int(row["koperasi_npwp"]) if not pd.isna(row["koperasi_npwp"]) else 0
            rat = int(row["koperasi_rat"]) if not pd.isna(row["koperasi_rat"]) else 0
            val = float(row["nilai_transaksi"]) if not pd.isna(row["nilai_transaksi"]) else 0.0
            label = int(row["cluster_label"]) if not pd.isna(row["cluster_label"]) else 0
            sql_lines.append(
                f"INSERT OR REPLACE INTO regencies (id, province_id, regency_name, jumlah_koperasi, koperasi_nib, koperasi_npwp, koperasi_rat, nilai_transaksi, cluster_label) "
                f"VALUES ({r_id}, {prov_id}, {escape_sql(name)}, {count}, {nib}, {npwp}, {rat}, {val}, {label});"
            )
        sql_lines.append("")

    # 3. Metrics
    if os.path.exists(MODEL_METRICS_JSON):
        logger.info("Membaca data Metrik...")
        sql_lines.append("-- Seed Metrics")
        with open(MODEL_METRICS_JSON, "r", encoding="utf-8") as f:
            metrics_data = json.load(f)
        metrics_obj = metrics_data.get("clustering_metrics", {})
        flat_metrics = {
            'silhouette_score': metrics_obj.get('silhouette_score'),
            'calinski_harabasz_index': metrics_obj.get('calinski_harabasz_index'),
            'davies_bouldin_index': metrics_obj.get('davies_bouldin_index'),
            'number_of_clusters': metrics_obj.get('number_of_clusters')
        }
        for key, val in flat_metrics.items():
            if val is not None:
                sql_lines.append(
                    f"INSERT OR REPLACE INTO metrics (key, value) "
                    f"VALUES ({escape_sql(key)}, {escape_sql(str(val))});"
                )
        sql_lines.append("")

    # 4. AI Report
    if os.path.exists(AI_REPORT_MD) and os.path.exists(AI_LABELS_JSON):
        logger.info("Membaca data Laporan AI...")
        sql_lines.append("-- Seed AI Report")
        with open(AI_REPORT_MD, "r", encoding="utf-8") as f:
            report_text = f.read()
        with open(AI_LABELS_JSON, "r", encoding="utf-8") as f:
            labels_json = f.read()
        sql_lines.append(
            f"INSERT OR REPLACE INTO ai_report (id, report_text, labels_json) "
            f"VALUES (1, {escape_sql(report_text)}, {escape_sql(labels_json)});"
        )
        sql_lines.append("")

    # Write to seed.sql
    os.makedirs(os.path.dirname(SEED_SQL), exist_ok=True)
    with open(SEED_SQL, 'w', encoding='utf-8') as f:
        f.write("\n".join(sql_lines))
    logger.info(f"SQL seed file generated at: {SEED_SQL}")

if __name__ == "__main__":
    main()
